//
//  InsightCard.swift
//  FlightApp
//
//  Displays Claude-generated insights with liquid glass styling
//

import SwiftUI

struct InsightCard: View {
    let type: InsightType
    let context: InsightContext
    let airlineColors: AirlineBrandColors?

    @StateObject private var viewModel = InsightsViewModel()
    @State private var isExpanded: Bool = false

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Header
            headerView

            // Content
            if isExpanded {
                contentView
                    .transition(.opacity.combined(with: .move(edge: .top)))
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .fixedSize(horizontal: false, vertical: true)
        .background(
            RoundedRectangle(cornerRadius: GlassConstants.cardCornerRadius)
                .fill(.ultraThinMaterial)
                .overlay(
                    RoundedRectangle(cornerRadius: GlassConstants.cardCornerRadius)
                        .fill(airlineColors?.color.opacity(0.15) ?? Color.blue.opacity(0.1))
                )
        )
        .overlay(
            RoundedRectangle(cornerRadius: GlassConstants.cardCornerRadius)
                .strokeBorder(Color.white.opacity(0.2), lineWidth: 1)
        )
        .onAppear {
            Task {
                await viewModel.loadInsight(type: type, context: context)
            }
        }
    }

    // MARK: - Header

    private var headerView: some View {
        Button {
            withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                isExpanded.toggle()
                HapticManager.shared.glassClick()
            }
        } label: {
            HStack {
                Image(systemName: iconName)
                    .font(.system(size: 16, weight: .medium))
                    .foregroundStyle(airlineColors?.color ?? .blue)

                Text(title)
                    .font(.system(size: 16, weight: .semibold))
                    .foregroundColor(.primary)

                Spacer()

                if viewModel.isLoading {
                    ProgressView()
                        .controlSize(.small)
                } else {
                    Image(systemName: isExpanded ? "chevron.up" : "chevron.down")
                        .font(.system(size: 14, weight: .semibold))
                        .foregroundColor(.secondary)
                }
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 14)
        }
        .buttonStyle(.plain)
    }

    // MARK: - Content

    private var contentView: some View {
        VStack(alignment: .leading, spacing: 12) {
            Divider()
                .background(Color.white.opacity(0.2))
                .padding(.horizontal, 16)

            if let error = viewModel.error {
                errorView(error)
            } else if let insight = viewModel.insight {
                insightTextView(insight)
            } else if viewModel.isLoading {
                loadingView
            }

            // Refresh button
            refreshButton
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(.horizontal, 16)
        .padding(.bottom, 14)
    }

    private func insightTextView(_ text: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(.init(text))
                .font(.system(size: 15))
                .foregroundColor(.primary)
                .lineSpacing(4)
                .fixedSize(horizontal: false, vertical: true)
                .multilineTextAlignment(.leading)
                .tint(airlineColors?.color ?? .blue)

            Text("Generated by Claude")
                .font(.system(size: 12))
                .foregroundColor(.secondary)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    private var loadingView: some View {
        HStack {
            ProgressView()
                .controlSize(.small)
            Text("Generating insight...")
                .font(.system(size: 14))
                .foregroundColor(.secondary)
        }
    }

    private func errorView(_ error: Error) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                Image(systemName: "exclamationmark.triangle.fill")
                    .foregroundColor(.orange)
                Text("Could not generate insight")
                    .font(.system(size: 14, weight: .medium))
                    .foregroundColor(.primary)
            }

            Text(error.localizedDescription)
                .font(.system(size: 13))
                .foregroundColor(.secondary)
        }
    }

    private var refreshButton: some View {
        Button {
            Task {
                HapticManager.shared.impact(.light)
                await viewModel.refresh(type: type, context: context)
            }
        } label: {
            HStack(spacing: 4) {
                Image(systemName: "arrow.clockwise")
                    .font(.system(size: 12, weight: .medium))
                Text("Refresh")
                    .font(.system(size: 13, weight: .medium))
            }
            .foregroundColor(airlineColors?.color ?? .blue)
        }
        .buttonStyle(.plain)
        .disabled(viewModel.isLoading)
        .opacity(viewModel.isLoading ? 0.5 : 1.0)
    }

    // MARK: - Helpers

    private var title: String {
        switch type {
        case .awardAnalysis:
            return "Award Insights"
        case .destination:
            return "Destination Info"
        case .routeContext:
            return "Route Context"
        case .aircraft:
            return "Aircraft Info"
        case .flightStatus:
            return "Flight Context"
        }
    }

    private var iconName: String {
        switch type {
        case .awardAnalysis:
            return "star.circle.fill"
        case .destination:
            return "location.circle.fill"
        case .routeContext:
            return "map.circle.fill"
        case .aircraft:
            return "airplane.circle.fill"
        case .flightStatus:
            return "clock.circle.fill"
        }
    }
}

// MARK: - Preview

#Preview {
    VStack(spacing: 16) {
        InsightCard(
            type: .destination,
            context: InsightContext(
                destinationAirport: "SFO",
                destinationCity: "San Francisco"
            ),
            airlineColors: nil
        )

        InsightCard(
            type: .awardAnalysis,
            context: InsightContext(
                awardData: [
                    AwardOffer(program: "United MileagePlus", miles: 70000, cabin: "Business"),
                    AwardOffer(program: "Air Canada Aeroplan", miles: 60000, cabin: "Business")
                ],
                origin: "JFK",
                destination: "LHR"
            ),
            airlineColors: AirlineColorService.shared.getBrandColors(for: "UA")
        )
    }
    .padding()
    .background(Color.black)
}
